apiVersion: v1
kind: Service
metadata:
  name: {{.Values.backend.service.name}}
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: {{.Values.backend.service.port}}
      targetPort: {{.Values.backend.deployment.port}}
  type: ClusterIP
