apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secrets
  namespace: {{.Release.Namespace}}
type: Opaque
stringData:
  POSTGRES_USER: "{{.Values.postgresql.config.postgresqlUsername}}"
  POSTGRES_PASSWORD: "{{.Values.postgresql.config.postgresqlPassword}}"
  POSTGRES_DB: "{{.Values.postgresql.config.postgresqlDatabase}}"
  DATABASE_URL: "postgresql://{{.Values.postgresql.config.postgresqlUsername}}:{{.Values.postgresql.config.postgresqlPassword}}@{{.Values.postgresql.service.name}}.{{.Release.Namespace}}:{{.Values.postgresql.service.port}}/{{.Values.postgresql.config.postgresqlDatabase}}"
