apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: {{.Release.Namespace}}
spec:
  selector:
    app: postgresql
  ports:
    - protocol: TCP
      port: {{.Values.postgresql.service.port}}
      targetPort: {{.Values.postgresql.deployment.port}}
  type: ClusterIP
